### ISSUE TITLE
OriginId is shown as uniswap in all the links after generating from Vote Delegation landing page.

### ISSUE THREAD

**Issue by abhishes007** [TokenScript-Framework/tlink#12]
OriginId is shown as uniswap in all the links after generating from Vote Delegation landing page.

Steps:
1. Visit Vote Delegation landing page and generate a TLink for any token other than uniswap.
2. Copy the Tlink and paste it in the browser.
3. Observe the OriginId value shown in the URL

Issue/Question:
1. Should the origin id for different tokens be different?
Right now what I observe is the originId is shown as uniswap for all the Tlinks generated.

Recording:

https://github.com/user-attachments/assets/364a504d-2165-4802-b003-9984412c56e0

cc: @futantan , @micwallace

**Comment by futantan** [comment]
fixed. I removed the originId

**Comment by abhishes007** [comment]
Verified Origin ID is removed from the Links:

Uploading chrome_emmvDWmTVp.mp4…
