### ISSUE TITLE
If a user has shared a card link then the link shown on Twitter post does not show the image.

### ISSUE THREAD

**Issue by abhishes007** [TokenScript-Framework/tlink#16]
If a user has shared a card link then the link shown on Twitter post does not show the image.

Steps:
1. Share a card link on X without having the Tlink extension enabled/installed.
2. Observe how the link is shown on X.

Issue:
If a user has shared a card link then the link shown on Twitter post does not show the image.

Ex: Shared link : https://tlink.store/tapp?chain=137&contract=0xd5ca946ac1c1f24eb26dae9e1a53ba6a02bd97fe#card=feedCat&originId=SmartCatNFT&tokenId=3925174527

Screenshot of how it appears on X:
![image](https://github.com/user-attachments/assets/cab88e4b-1d21-4b95-82ec-da6da048e7aa)

**Comment by futantan** [comment]
![CleanShot 2024-11-15 at 10 26 46@2x](https://github.com/user-attachments/assets/33433c07-59fd-4bad-acdc-20b114c2e118)
hi @abhishes007 the url you shared should contain a tokenId in the query part(its' only in the hash part now)

try this: https://tlink.store/tapp?chain=137&contract=0xd5ca946ac1c1f24eb26dae9e1a53ba6a02bd97fe&tokenId=3925174527#card=feedCat&originId=SmartCatNFT&tokenId=3925174527
